version: '2'

services:
  app:
    build: .
    image: ubuntu
  unit:
    image: ubuntu
    command: bash -c "echo hello world"
  production:
    image: ubuntu:${BUILD_NUMBER}
    ports:
      - 10001:4567
