version: '2'

services:
  app:
    build: .
    image: ${DOCKER_USER_ID}/docker-jenkins
  unit:
    image: docker-jeckins:2
    volumes:
      - ${WORKSPACE_PATH}/${JOB_NAME}:/app
    working_dir: /app
    command: bash -c "echo hello world"
  production:
    image: ${DOCKER_USER_ID}/docker-jenkins:${BUILD_NUMBER}
    ports:
      - 10001:4567
