version: '2'

services:
  app:
    build: .
    image: geonhee/ubuntu
  unit:
    image: geonhee/ubuntu
    command: bash -c "echo hello world"
  production:
    image: geonhee/ubuntu:${BUILD_NUMBER}
