version: '2'

services:
  app:
    build: .
    image: docker-jenkins/ubuntu
  unit:
    image: docker-jenkins/ubuntu
    command: bash -c "echo hello world"
  production:
    image: docker-jenkins/ubuntu:${BUILD_NUMBER}
    ports:
      - 10001:4567
