version: '2'

services:
  app:
    build: .
    image: ${DOCKER_USER_ID}/ubuntu
  unit:
    image: ${DOCKER_USER_ID}/ubuntu
    command: bash -c "echo hello world"
  production:
    image: ${DOCKER_USER_ID}/ubuntu:${BUILD_NUMBER}
